In [1]:
import numpy as np

In [ ]:
#creating array from list


In [2]:
arr1 = np.array([1,2,3,4,5])
print("id array", arr1)

id array [1 2 3 4 5]


In [3]:
#2d array

arr2 = np.array([[1,2,3],[4,5,6]])
print("2d array" , arr2)

2d array [[1 2 3]
 [4 5 6]]


In [ ]:
#list vs numpy

In [4]:
py_list = [1,2,3]
print("python list multiplication", py_list*2)

python list multiplication [1, 2, 3, 1, 2, 3]


In [ ]:
#numpy array

In [5]:
np_arry = np.array([1,2,3])
print("python array muliplication ", np_arry*2)

python array muliplication  [2 4 6]


In [6]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n Numpy operation time: ", time.time()-start)


 Numpy operation time:  0.09301471710205078


In [8]:
start = time.time()
np_array = np.arange(10000000) * 2
print("\n Numpy operation time :" , time.time()-start)


 Numpy operation time : 0.05451035499572754


In [ ]:
#creating array from scartch

In [10]:
zeros = np.zeros((5,4))
print("zeros array : \n", zeros)  #5 rows and 4 columns

zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
ones = np.ones((2,3))
print("one array: \n",ones) #2 rows and 3 columsn

one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
full = np.full((2,2),7)
print("full array \n", full)  #it fill the 7 in 2 both column an both rows

full array 
 [[7 7]
 [7 7]]


In [13]:
random = np.random.random((2,3))
print("random array: \n", random)

random array: 
 [[0.99815146 0.5564098  0.2030193 ]
 [0.48897279 0.54079236 0.53795967]]


In [14]:
sequnce = np.arange(0,11,2)
print ("sequence array:",sequnce )  # this will step every 2 steps

sequence array: [ 0  2  4  6  8 10]


In [ ]:
#vector , matrix , tensor

In [15]:
vector = np.array([1,2,3])
print("vector:" , vector)   # considered as a one-dimensional array

vector: [1 2 3]


In [16]:
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("matrix: ", matrix)

matrix:  [[1 2 3]
 [4 5 6]]


In [17]:
tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor:" , tensor)

tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#
#Array properties

In [18]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("shape", arr.shape)  #check the how many rows ans columsn


shape (2, 3)


In [19]:
print("dimension ", arr.ndim)

dimension  2


In [20]:
print("size",arr.size)

size 6


In [21]:
print("DType ", arr.dtype)  #info related the arrat

DType  int64


In [ ]:
#
#Array Reshaping

In [25]:
arr=np.arange(12)
print("original array" , arr)

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped) # it put the values in 3 rows and 4 column


 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
flattened = reshaped.flatten()
print("\n flattened array", flattened)


 flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [30]:
transpose= reshaped.T
print("\n raveled array ", transpose)


 raveled array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
#Numpy Array operations

In [33]:
arr= np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing ", arr[2:7])

Basic slicing  [3 4 5 6 7]


In [36]:
print("with steps",arr[1:8:2])    # it go from start to 8 with jump every 2 steps


with steps [2 4 6 8]


In [37]:
print("negative indexing ", arr[-3])  # it go from end array

negative indexing  8


In [38]:
arr_2 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("specific element ", arr_2[1,2])

specific element  6


In [40]:
print("entire row", arr_2[1])

entire row [4 5 6]


In [45]:
print("Entire row: ", arr_2[:, 1])

Entire row:  [2 5 8]


In [ ]:
#sorting

In [46]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("sorted Array ", np.sort(unsorted))  # this sort the array

sorted Array  [1 1 2 3 4 5 6 9]


In [47]:
arr_2d_unorered = np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array by column", np.sort(arr_2d_unorered,axis = 0))

sorted 2d array by column [[1 1]
 [2 2]
 [3 3]]


In [ ]:
#
#Filter

In [48]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("even number", even_number)

even number [ 2  4  6  8 10]


In [ ]:
#
#Filter with mask

In [52]:
masks = numbers >5
print("numbers greater than 5", numbers[masks])

numbers greater than 5 [ 6  7  8  9 10]


In [ ]:
#Fancy indexing vs np.where()

In [53]:
indices = [0, 2, 4]   #[1,2,3,4,5,6,7,8,9,10]
print(numbers[indices])  # it check the number line and it

[1 3 5]


In [54]:
where_result = np.where(numbers > 5)
print(where_result)

(array([5, 6, 7, 8, 9]),)


In [55]:
print("NP where", numbers[where_result])

NP where [ 6  7  8  9 10]


In [56]:
#Adding and removing data
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


In [ ]:

#array compatibilty

In [58]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("compatibility shapes", a.shape == b.shape)

compatibility shapes True


In [59]:
a = np.array([1,2,3])
b = np.array([4,5,6,4])
c = np.array([7,8,9])
print("compatibility shapes", a.shape == b.shape)

compatibility shapes False


In [60]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original, new_row))
print(original)

[[1 2]
 [3 4]]


In [61]:
print(with_new_row)

[[1 2]
 [3 4]
 [5 6]]


In [62]:
new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("with new column", with_new_col)

with new column [[1 2 7]
 [3 4 8]]


In [63]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("array after delation:" , deleted)   # it deleted the array with helo of index

array after delation: [1 2 4 5]
